config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  mount Resque::Server.new, at: "/resque"

  get 'trainings/train'

  get 'fights/show'

  devise_for :users

  root 'pages#homepage'

  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  resources :training
  resources :robots, only: [:create, :destroy]
  resources :skills, only: [] do
    member do
      post :activate
      post :deactivate
      get :invoke

      get 'train/:name', to: 'trainings#train', as: 'train'
      post 'train/:name', to: 'trainings#submit', as: 'submit_training'
    end
  end
  resources :fights, only: [:create, :show]
end

app/models/fight.rb
class Fight < ActiveRecord::Base
  belongs_to :challenger, class_name: 'Robot'
  belongs_to :challengee, class_name: 'Robot'
end

app/models/robot.rb
class Robot < ActiveRecord::Base
  CATEGORY_NAMES = {
    ee: 'Electrical Engineering',
    meche: 'Mechanical Engineering'
  }

  DEFAULT_SKILLSET = {
    base: [:rumble, :squeal],
    ee: [:short_circuit],
    meche: [:oil]
  }

  DEFAULT_IMAGE_URI = {
    base: "https://placehold.it/400x250",
    ee: "http://i.imgur.com/ThumYo2.jpg",
    meche: "http://i.imgur.com/bf0llYo.jpg"
  }

  MAX_ACTIVE_SKILLS = 4

  belongs_to :user
  has_many :skills

  enum category: [:ee, :meche]

  before_create :fetch_category
  before_create :set_defaults
  after_create :grant_base_skills

  def category_name
    CATEGORY_NAMES[self.category.to_sym]
  end

  def max_health
    8 + 2 * self.level
  end

  def heal
    self.health = self.max_health
    self.save!
  end

  private
    def set_defaults
      self.level = 1
      self.strength = 10
      self.speed = 10
      self.health = 10
      self.experience = 0
      self.image_uri = DEFAULT_IMAGE_URI[self.category.to_sym]
      puts self.image_uri
      true
    end

    def grant_base_skills
      [:base, self.category.to_sym].each do |set|
        DEFAULT_SKILLSET[set].each do |s|
          self.skills.create!(category: s)
        end
      end
      true
    end

    def fetch_category
      client = Particle.new('7941c28d0fca23c2efbe75bbd0f0d6ad81210f5c', self.identifier)
      self.category = client.get_device_variable('category')
      true
    end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  belongs_to :robot
  has_many :trainings

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  CATEGORY_NAMES = {
    rumble: 'Rumble',
    squeal: 'Squeal',
    punch: 'Punch',
    buckle: 'Buckle',
    oil: 'Oil',
    light_eyes: 'Light Eyes',
    raise_voltage: 'Raise Voltage',
    short_circuit: 'Short Circuit'
  }

  enum category: [:rumble, :squeal, :punch, :buckle, :oil, :light_eyes, :raise_voltage, :short_circuit]

  before_create :set_defaults

  def category_name
    CATEGORY_NAMES[self.category.to_sym]
  end

  def activate
    return false if self.robot.skills.active.size == Robot::MAX_ACTIVE_SKILLS
    self.active = true
    self.save!
    return true
  end

  def deactivate
    self.active = false
    self.save!
    return true
  end

  def has_completed_training?(name)
    self.trainings.where(name: name).any?
  end

  def invoke!
    Resque.enqueue(InvokeSkill, self.id)
  end
  
  private
    def set_defaults
      self.level = 1
      self.experience = 0
      self.active = false
      true
    end

end

app/models/training.rb
class Training < ActiveRecord::Base
  belongs_to :skill

  def self.trainings_for(skill)
    trainings[skill.category.to_s] || []
  end

  def self.available_trainings_for(skill)
    trainings_for(skill).select do |t|
      !skill.has_completed_training?(t['name'])
    end.select do |t|
      (!t['prereq'].present?) || skill.has_completed_training?(t['prereq'])
    end
  end

  def self.next_training_for(skill)
    self.available_trainings_for(skill).first
  end

  def self.has_available_trainings_for?(skill)
    !self.next_training_for(skill).nil?
  end

  def self.training_with_name(name)
    trainings.map do |k, v|
      v.detect { |t| t['name'] == name }
    end.compact.first
  end

  private
    def self.trainings
      JSON.parse(File.read(File.join(Rails.root, 'app/assets/trainings.json')))
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :robots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def show
    @fight = Fight.find(params[:id])

    @bot_a, @bot_b = @fight.challenger, @fight.challengee
    @bot_a, @bot_b = @bot_b, @bot_a if @bot_a.user == current_user
  end

  def create
    @fight = Fight.create!(fight_params)
    @fight.challenger.heal
    @fight.challengee.heal
    redirect_to @fight
  end

  private
    def fight_params
      params.require(:fight).permit(:challenger_id, :challengee_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]

  def homepage
  end

  def dashboard
    @robots = current_user.robots.all
    @current_robot = @robots.first
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    current_user.robots.create!(robot_params)
    redirect_to dashboard_path
  end

  private
    def robot_params
      params.require(:robot).permit(:name, :identifier)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def activate
    @skill = Skill.find(params[:id])
    @success = @skill.activate
  end

  def deactivate
    @skill = Skill.find(params[:id])
    @success = @skill.deactivate
  end

  def invoke
    @skill = Skill.find(params[:id])
    @opponent = Robot.find(params[:opponent])
    @opponent.health -= 2
    @opponent.save!
    @skill.invoke!
    redirect_to :back
  end
end

app/controllers/training_controller.rb
class TrainingController < ApplicationController

    def index
    end

end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  def train
    @skill = Skill.find(params[:id])
    @training_name = params[:name]
    @training = Training.training_with_name(@training_name)

    @questions = @training['questions']
  end

  def submit
    @skill = Skill.find(params[:id])
    @training_name = params[:name]
    @training = Training.training_with_name(@training_name)
    @wrong = []
    @answers = []

    @training['questions'].each_with_index do |q, i|
      @wrong << i unless params["answer_#{i}"].to_i == q['answer']
      @answers << params["answer_#{i}"].to_i
    end

    if @wrong.empty?
      @skill.level += 1
      @skill.save! 
      @skill.trainings.create!(name: @training_name)

      redirect_to dashboard_path
    else
      @questions = @training['questions']
      render 'train', locals: {wrong: @wrong, answers: @answers}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def name
    'Hackbots'
  end
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/fights/show.haml
- [[@bot_a, "botA"], [@bot_b, "botB"]].each do |bot|
  - b = bot[0]
  .bot-container{id: bot[1]}
    .uk-panel.uk-panel-box
      .uk-panel-teaser
        %img{"src" => "#{b.image_uri}"}

      %h3= b.name
      %p.description= "Level #{b.level}"
      %p.description= "#{b.category_name} Bot"
      #hp.uk-progress.uk-progress-success
        .uk-progress-bar{style: "width: #{(100.0 * b.health / b.max_health).to_i}%; "}
          %span.health= b.health
          /
          %span.max_health= b.max_health

.menu-container
  %ul.tabs.uk-tab{"data-uk-tab" => "{connect: '#menu'}"}
    %li.uk-active
      %a{:href => ""}= @bot_a.name
    %li
      %a{:href => ""}= @bot_b.name
  %ul#menu.uk-switcher.uk-margin
    - [[@bot_a, @bot_b],[@bot_b, @bot_a]].each do |bot|
      %li.uk-active
        .uk-grid#menu-grid
          .uk-width-1-2
            #text.uk-panel.uk-panel-box
              Select an action...
          .uk-width-1-2
            #skills.uk-grid.uk-grid-small{"data-uk-grid-match" => "", "data-uk-grid-margin" => ""}
              - 0.upto(3) do |i|
                - unless bot[0].skills.active.size <= i
                  %a.skill.uk-width-1-2{"href" => "/skills/#{bot[0].skills.active[i].id}/invoke?opponent=#{bot[1].id}"}
                    .uk-panel.uk-panel-box
                      %p= bot[0].skills.active[i].category_name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= name
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body{id: controller_name + '_' + action_name}
    %nav.uk-navbar.cl-navbar
      .uk-container.uk-container-center
        %a.uk-navbar-brand{href: root_path}= name
        .uk-navbar-flip
          %ul.uk-navbar-nav
            - if user_signed_in?
              %li
                %a{href: dashboard_path} Dashboard
              %li
                = link_to 'Sign Out', destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Join', new_user_registration_path
              %li
                = link_to 'Login', new_user_session_path
    .uk-container.uk-container-center#container
      - if notice.present?
        %p.notice= notice
      - if alert.present?
        %p.alert= alert
      = yield

app/views/pages/_skills.haml
- skills.each do |s|
  .skill{'data-skill-id' => s.id}
    %p.name= s.category_name
    %p.description= "Level #{s.level}"
    = link_to 'Activate', activate_skill_path(s), method: :post, class: 'activate', data: {remote: true}
    = link_to 'Deactivate', deactivate_skill_path(s), method: :post, class: 'deactivate', data: {remote: true}
    - if Training.has_available_trainings_for?(s)
      = link_to 'Training Available', train_skill_path(s, Training.next_training_for(s)['name']), class: 'training' 

app/views/pages/dashboard.haml
%h2 Dashboard

#new_robot.uk-modal
  .uk-modal-dialog
    %a.uk-modal-close.uk-close
    %h3 Add Bot
    = form_for current_user.robots.new, html: {class: 'modal-form'} do |f|
      = f.text_field :name, placeholder: 'Name of the bot. '
      = f.text_field :identifier, placeholder: 'Identifier of the bot. '
      = f.submit 'Add Bot'

= form_for Fight.new do |f|
  = f.hidden_field :challenger_id
  = f.hidden_field :challengee_id

#challenge_robot.uk-modal
  .uk-modal-dialog
    %a.uk-modal-close.uk-close
    %h3 Challenge Other Bots
    - Robot.all.each do |r|
      = link_to 'Challenge ' + r.name, '#', class: 'button challenge-button', data: {'robot-id' => r.id}

.uk-grid
  .uk-width-1-4
    - @robots.each do |r|
      %a.robot{'data-robot-id' => r.id}
        %h3.name= r.name
        %p.description= "Level #{r.level}"
        %p.description= "#{r.category_name} Bot"

    = link_to 'Add Bot', '#new_robot', class: 'button', data: {'uk-modal' => ''}

  .uk-width-3-4
    - @robots.each do |r|
      .robot-detail{'data-robot-id' => r.id}
        .health
          .max &nbsp;
          .current{style: "width: #{(100.0 * r.health / r.max_health).to_i}%; "}= "#{r.health} / #{r.max_health}"
        .uk-grid.stats
          .uk-width-1-3
            %p.label= "Strength: #{r.strength}"
          .uk-width-1-3
            %p.label= "Speed: #{r.speed}"
          .uk-width-1-3
            %p.label= "Experience: #{r.experience}"
        .challenge
          = link_to 'Challenge Other Bots! ', '#challenge_robot', class: 'button danger', data: {'uk-modal' => ''}
        .uk-grid.skills
          .uk-width-1-2.available
            %h3 Available skills
            = render 'skills', skills: r.skills.inactive, active: false
          .uk-width-1-2.active
            %h3 Active skills
            = render 'skills', skills: r.skills.active, active: true

app/views/pages/homepage.html.haml
%h1 Welcome to Callisto

app/views/skills/activate.js.erb
<% if @success %>
  var robot = $('.robot-detail[data-robot-id=' + <%= @skill.robot.id %> + ']');
  var skill = robot.find('[data-skill-id=' + <%= @skill.id %> +']');
  skill.detach().appendTo(robot.find('.skills .active'));
  skill.find('.activate').hide()
  skill.find('.deactivate').show()
<% else %>
  alert('Cannot activate skill. Each robot can have at most ' + <%= Robot::MAX_ACTIVE_SKILLS %> + ' skills active at the same time. ');
<% end %>

app/views/skills/deactivate.js.erb
<% if @success %>
  var robot = $('.robot-detail[data-robot-id=' + <%= @skill.robot.id %> + ']');
  var skill = robot.find('[data-skill-id=' + <%= @skill.id %> +']');
  skill.detach().appendTo(robot.find('.skills .available'));
  skill.find('.deactivate').hide()
  skill.find('.activate').show()
<% else %>
  alert('Cannot deactivate skill. ');
<% end %>

app/views/training/index.html.haml
%h2 Training

app/views/trainings/train.html.haml
%h2 Skill Training

- wrong = [] if local_assigns[:wrong].nil?
- answers = nil if local_assigns[:answers].nil?

= form_tag submit_training_skill_path(@skill, @training_name) do
  - @questions.each_with_index do |q, question_id|
    .question{class: wrong.include?(question_id) ? 'wrong' : ''}
      %p.prompt= q['prompt']
      - q['choices'].each_with_index do |c, answer|
        = radio_button_tag "answer_#{question_id}", answer, answers && answers[question_id] == answer
        = label_tag "answer_#{question_id}_#{answer}", c
        %br/
  = submit_tag 'Submit Your Answers'